env:
  es2021: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - '@typescript-eslint'

rules:
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-object-literal-type-assertion': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-parameter-properties': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: true
