declare const CONFIG: {
  ALGOLIA_APP_ID: string;
  ALGOLIA_API_KEY: string;
  ALGOLIA_INDEX_PUBLICATION: string;
  ALGOLIA_INDEX_PUBLICATION_CONTENT: string;
  ALGOLIA_INDEX_PUBLICATION_SUGGESTION: string;
};

export const {
  ALGOLIA_APP_ID,
  ALGOLIA_API_KEY,
  ALGOLIA_INDEX_PUBLICATION,
  ALGOLIA_INDEX_PUBLICATION_CONTENT,
  ALGOLIA_INDEX_PUBLICATION_SUGGESTION
} = CONFIG;
